"""
Ticketing Agent — OpsPilot
Responsible for:
- Creating, updating, or closing tickets in Jira/ServiceNow
- Attaching logs & resolution details automatically
Maps to Proposal Section 5.1.2: Ticketing Agent
"""

import os


class TicketingAgent:
    """
    Ticketing Agent — Manages full Jira ticket lifecycle.
    Creates tickets with LLM-generated rich descriptions.
    """

    def __init__(self, jira_connector=None):
        self.jira = jira_connector

    def create_ticket(self, incident_id: str, incident_type: str, analysis: dict) -> str:
        """
        Creates a Jira ticket with rich AI-generated content.
        Returns ticket key.
        """
        if not self.jira:
            print(f"[TicketingAgent] No Jira connector. Skipping ticket for {incident_id}.")
            return None

        severity = analysis.get("severity", "P2")
        root_cause = analysis.get("root_cause", "Unknown")
        action = analysis.get("top_recommendation", "Escalate")
        summary = analysis.get("summary", "IT Incident Detected")
        reasoning = analysis.get("reasoning", "")
        evidence = analysis.get("evidence", "")

        short_cause = root_cause[:80] if root_cause else "Unknown"
        ticket_summary = f"[OpsPilot AI] {incident_type.replace('_', ' ').title()} — {short_cause}"

        description = (
            f"## AI Root Cause Analysis\n"
            f"{root_cause}\n\n"
            f"## Symptoms Observed\n"
            f"{summary}\n\n"
            f"## Recommended Action\n"
            f"{action}\n\n"
            f"## Diagnostic Evidence\n"
            f"{evidence}\n\n"
            f"## Agent Reasoning\n"
            f"{reasoning}\n\n"
            f"---\n"
            f"*Generated by OpsPilot Autonomous IT Agent | Incident: {incident_id} | Severity: {severity}*"
        )

        ticket_key = self.jira.create_ticket({
            "summary": ticket_summary,
            "root_cause": description,
            "severity": severity
        })

        print(f"[TicketingAgent] Created ticket: {ticket_key} for {incident_id}")
        return ticket_key

    def resolve_ticket(self, ticket_key: str, resolution_log: str) -> bool:
        """Closes/resolves a ticket with resolution details."""
        if not self.jira or not ticket_key:
            return False
        comment = f"✅ Resolved by OpsPilot Autonomous Agent.\n\nResolution Log:\n{resolution_log}"
        return self.jira.update_status(ticket_key, "RESOLVED", comment)

    def escalate_ticket(self, ticket_key: str, reason: str) -> bool:
        """Escalates a ticket to L3 with reason."""
        if not self.jira or not ticket_key:
            return False
        comment = (
            f"⚠️ Escalated to L3 Support.\n\n"
            f"Reason: {reason}\n"
            f"The AI agent's proposed action was denied by the operator."
        )
        return self.jira.update_status(ticket_key, "ESCALATED", comment)

    def add_diagnostic_comment(self, ticket_key: str, diagnostic_results: dict) -> bool:
        """Attaches diagnostic results as a comment to the ticket."""
        if not self.jira or not ticket_key:
            return False
        import json
        comment = "## Diagnostic Tool Results\n```\n"
        for check, result in diagnostic_results.get("checks", {}).items():
            comment += f"{check}: {json.dumps(result, indent=2)}\n"
        comment += "```"
        return self.jira.update_status(ticket_key, "OPEN", comment)
